name: shuruhat_new
description: A new Flutter project.
publish_to: 'none'

# رفع رقم الإصدار لتجاوز النسخة الحالية على Play Store (versionCode > 34)
version: 1.3.3+38

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  google_fonts: ^6.1.0
  photo_view: ^0.14.0
  flutter_carousel_slider: ^1.1.0
  video_player: ^2.7.2
  chewie: ^1.7.4
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  path_provider: ^2.1.3
  open_filex: ^4.3.2
  google_mobile_ads: ^4.0.0
  provider: ^6.1.1
  in_app_purchase: ^3.2.3
  audioplayers: ^6.5.0
  shared_preferences: ^2.0.15
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# إذا استمر تعارض http مع أي حزمة، هذه الوسيلة تُرغم استخدام النسخة المطلوبة
dependency_overrides:
  http: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    # ضمّم هنا مجلّد الأصوات (correct.mp3 و wrong.mp3) وأي أصول أخرى
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
